# Generated by Django 6.0.5 on 2026-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patients_seen', models.IntegerField(default=0)),
                ('avg_consult_time', models.FloatField(default=0.0)),
                ('total_hours_worked', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_patients', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_emergency_cases', models.IntegerField(default=0)),
                ('average_wait_time', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
