# Generated by Django 6.0.5 on 2026-05-14 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_number', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('NO_SHOW', 'NO_SHOW')], default='PENDING', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
