# Generated by Django 6.0.5 on 2026-05-14 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('token_number', models.CharField(max_length=50, unique=True)),
                ('estimated_wait_time', models.PositiveIntegerField(default=0)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('ai_priority_score', models.FloatField(default=0)),
                ('emergency_case', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
