QUEUE_STATUS_WAITING = "WAITING"
QUEUE_STATUS_IN_PROGRESS = "IN_PROGRESS"
QUEUE_STATUS_COMPLETED = "COMPLETED"
QUEUE_STATUS_CANCELLED = "CANCELLED"

PATIENT_PRIORITY_LOW = 1
PATIENT_PRIORITY_MEDIUM = 2
PATIENT_PRIORITY_HIGH = 3
PATIENT_PRIORITY_CRITICAL = 4